/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsMotherlessHomeRouteImport } from './routes/programs.motherless-home'
import { Route as ProgramsEmpowermentRouteImport } from './routes/programs.empowerment'
import { Route as ProgramsElderlyCareRouteImport } from './routes/programs.elderly-care'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsMotherlessHomeRoute = ProgramsMotherlessHomeRouteImport.update({
  id: '/motherless-home',
  path: '/motherless-home',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsEmpowermentRoute = ProgramsEmpowermentRouteImport.update({
  id: '/empowerment',
  path: '/empowerment',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsElderlyCareRoute = ProgramsElderlyCareRouteImport.update({
  id: '/elderly-care',
  path: '/elderly-care',
  getParentRoute: () => ProgramsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/stories': typeof StoriesRoute
  '/volunteer': typeof VolunteerRoute
  '/programs/elderly-care': typeof ProgramsElderlyCareRoute
  '/programs/empowerment': typeof ProgramsEmpowermentRoute
  '/programs/motherless-home': typeof ProgramsMotherlessHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/stories': typeof StoriesRoute
  '/volunteer': typeof VolunteerRoute
  '/programs/elderly-care': typeof ProgramsElderlyCareRoute
  '/programs/empowerment': typeof ProgramsEmpowermentRoute
  '/programs/motherless-home': typeof ProgramsMotherlessHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/stories': typeof StoriesRoute
  '/volunteer': typeof VolunteerRoute
  '/programs/elderly-care': typeof ProgramsElderlyCareRoute
  '/programs/empowerment': typeof ProgramsEmpowermentRoute
  '/programs/motherless-home': typeof ProgramsMotherlessHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/programs'
    | '/stories'
    | '/volunteer'
    | '/programs/elderly-care'
    | '/programs/empowerment'
    | '/programs/motherless-home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/programs'
    | '/stories'
    | '/volunteer'
    | '/programs/elderly-care'
    | '/programs/empowerment'
    | '/programs/motherless-home'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/programs'
    | '/stories'
    | '/volunteer'
    | '/programs/elderly-care'
    | '/programs/empowerment'
    | '/programs/motherless-home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  StoriesRoute: typeof StoriesRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/motherless-home': {
      id: '/programs/motherless-home'
      path: '/motherless-home'
      fullPath: '/programs/motherless-home'
      preLoaderRoute: typeof ProgramsMotherlessHomeRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/empowerment': {
      id: '/programs/empowerment'
      path: '/empowerment'
      fullPath: '/programs/empowerment'
      preLoaderRoute: typeof ProgramsEmpowermentRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/elderly-care': {
      id: '/programs/elderly-care'
      path: '/elderly-care'
      fullPath: '/programs/elderly-care'
      preLoaderRoute: typeof ProgramsElderlyCareRouteImport
      parentRoute: typeof ProgramsRoute
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsElderlyCareRoute: typeof ProgramsElderlyCareRoute
  ProgramsEmpowermentRoute: typeof ProgramsEmpowermentRoute
  ProgramsMotherlessHomeRoute: typeof ProgramsMotherlessHomeRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsElderlyCareRoute: ProgramsElderlyCareRoute,
  ProgramsEmpowermentRoute: ProgramsEmpowermentRoute,
  ProgramsMotherlessHomeRoute: ProgramsMotherlessHomeRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  StoriesRoute: StoriesRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
